DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Topic;
DROP TABLE IF EXISTS Forum;
DROP TABLE IF EXISTS Person;

CREATE TABLE Person (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(10) NOT NULL UNIQUE,
    stuId VARCHAR(10) NULL
);

CREATE TABLE Forum (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Topic (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL UNIQUE,
    forumId INTEGER NOT NULL,
    FOREIGN KEY (forumId) REFERENCES Forum(id)
);

CREATE TABLE Post (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    topicId INTEGER NOT NULL,
    authorId INTEGER NOT NULL,
    text VARCHAR(100) NOT NULL,
    postedAt VARCHAR(50) NOT NULL,
    FOREIGN KEY (topicId) REFERENCES Topic(id),
    FOREIGN KEY (authorId) REFERENCES Person(id)
);




